
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 28 02:06:09 BST 2018
//----------------------------------------------------

package JSONCompiler;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int NUM = 10;
  public static final int LSQBRACKET = 4;
  public static final int BOOL = 11;
  public static final int COLON = 3;
  public static final int STR = 9;
  public static final int NULL = 8;
  public static final int RSQBRACKET = 5;
  public static final int EOF = 0;
  public static final int LCUBRACKET = 6;
  public static final int error = 1;
  public static final int COMMA = 2;
  public static final int RCUBRACKET = 7;
}

